// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}
interface FileAPI {
  openFile: () => Promise<{ fileName: string; content: string } | null>;
  saveFile: (fileName: string, content: string) => Promise<boolean>;
  /** Get the filesystem path from a dropped File object */
  getPathForFile: (file: File) => string;
}

interface DebugAPI {
  log: (
    level:
      | "info"
      | "success"
      | "warn"
      | "error"
      | "debug"
      | "route"
      | "file"
      | "ipc",
    message: string,
    ...args: unknown[]
  ) => void;
  info: (message: string, ...args: unknown[]) => void;
  success: (message: string, ...args: unknown[]) => void;
  warn: (message: string, ...args: unknown[]) => void;
  error: (message: string, ...args: unknown[]) => void;
  debug: (message: string, ...args: unknown[]) => void;
  route: (message: string, ...args: unknown[]) => void;
  file: (message: string, ...args: unknown[]) => void;
  ipc: (message: string, ...args: unknown[]) => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  fileAPI: FileAPI;
  debugAPI: DebugAPI;
  settingsAPI: {
    getLanguage: () => Promise<"pl" | "en">;
    setLanguage: (lang: "pl" | "en") => Promise<"pl" | "en">;
  };
  updaterAPI: {
    // Commands
    startDownload: () => void;
    installNow: () => void;
    checkForUpdates: () => void;
    // DEV ONLY: Test methods
    _testShowUpdate: () => void;
    _testSimulateDownload: () => void;
    // Event listeners
    onCheckingForUpdate: (callback: () => void) => () => void;
    onUpdateAvailable: (
      callback: (info: {
        version: string;
        releaseNotes: string | null;
        releaseDate: string;
      }) => void,
    ) => () => void;
    onUpdateNotAvailable: (
      callback: (info: { version: string }) => void,
    ) => () => void;
    onDownloadProgress: (
      callback: (progress: {
        bytesPerSecond: number;
        percent: number;
        transferred: number;
        total: number;
      }) => void,
    ) => () => void;
    onUpdateDownloaded: (
      callback: (info: {
        version: string;
        releaseNotes: string | null;
        releaseDate: string;
      }) => void,
    ) => () => void;
    onUpdateError: (callback: (error: string) => void) => () => void;
  };
}
